### ISSUE TITLE
¡Stop this chromosome discrimination!

### ISSUE THREAD

**Issue by ghost** [baezortega/somatypus#4]
Yo man, your tool here is nice - but I can no longer accept the discriminatory nature of your code against organisms with large chromosomes!

I mean really large chromosomes, larger than yours. Think about [marsupials](https://www.ebi.ac.uk/ena/data/view/PRJEB35073), for example. Plants, big genome plants. Or what would the [Marbled lungfish](https://en.wikipedia.org/wiki/Marbled_lungfish) say if you can't run somatypus on him? "Speciesism!"

[CSI indexing on VCFs and BAM files is the future](https://github.com/samtools/htsjdk/issues/447), I tell ya bro. Check out my brand new golden changes to your core bash script, here attached. 

No questions. Peace out.

[somatypus_1.3_big_chromosomes.zip](https://github.com/baezortega/somatypus/files/4245609/somatypus_1.3_big_chromosomes.zip)

**Comment by baezortega** [comment]
Thank you for your interest in Somatypus. Unfortunately this tool is no longer maintained. I wish you best of luck in your future variant calling efforts.
